name: Get Covid Data
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '00 18 * * *'
jobs:
  covid:
    name: Covid
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Go Code
        run: go run .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: daily update
