name: Get Covid Data
on:
  push:
    branches:
      - master
  schedule:
    - cron: "00 7,19 * * *"
jobs:
  covid:
    name: Covid
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Go Code
        run: go run .

      - name: Commit results
        run: |
          set -e
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          d="$(date --rfc-3339=s)"
          git add .
          git commit  -m "Periodic update: $d"
          git push origin master
